[package]
name = "perfcnt"
version = "0.0.1"
authors = ["Gerd Zellweger <mail@gerdzellweger.com>"]
description = "Library to configure and read hardware performance counters in rust."
homepage = "https://github.com/gz/rust-perfcnt"
repository = "https://github.com/gz/rust-perfcnt"
documentation = "http://gz.github.io/rust-perfcnt/perfcnt/"
readme = "README.md"
keywords = ["amd64", "x86", "performance", "counter", "hardware"]
license = "MIT"

build = "build.rs"

[build-dependencies.phf_codegen]
phf_codegen = "0.7.5"

[build-dependencies.serde_json]
serde_json = "0.6.0"

[build-dependencies.csv]
csv = "0.14.3"

[dependencies.bitflags]
bitflags = "*"

[dependencies.libc]
libc = "0.1.10"

[dependencies.x86]
x86 = "*"

[dependencies.phf]
git = "https://github.com/sfackler/rust-phf.git"
features = ["core"]
