[package]
name = "perfcnt"
version = "0.0.2"
authors = ["Gerd Zellweger <mail@gerdzellweger.com>"]
description = "Library to configure and read hardware performance counters in rust."
homepage = "https://github.com/gz/rust-perfcnt"
repository = "https://github.com/gz/rust-perfcnt"
documentation = "http://gz.github.io/rust-perfcnt/perfcnt/"
readme = "README.md"
keywords = ["amd64", "x86", "performance", "counter", "hardware"]
license = "MIT"

[dependencies]
bitflags = "*"
libc = "0.1.10"
x86 = "*"

[[bin]]
name = "perfcnt-list"
path = "src/bin/list.rs"
